runtime: nodejs12
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Handles all non https requests
#- url: /.*
#  secure: always
#  redirect_http_response_code: 301
#  script: auto
  # Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
