# [START cloudbuild_npm_node]
steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ['install', '--save-exact']
  # Run custom commands
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: gcr.io/cloud-builders/gcloud
    args: [ app, deploy ]
# [END cloudbuild_npm_node]
