import arr from '../data/SuggestedWords.json'
import React, { Component, useEffect, useState } from 'react'
import { Form, Button, Alert } from 'react-bootstrap'

const resetGameTwoPlayer = (props) => {
  props.setPlayer1Word('')
  props.setPlayer1WordList([])
  props.setPlayer2Word('')
  props.setPlayer2WordList([])
  props.setPlayer2Name("Player 2")
  props.setPlayer1Numbers([])
  props.setPlayer2Numbers([])
  props.setPlayer1NumbersMedium([])
  props.setPlayer2NumbersMedium([])
  props.setWin(0)
  props.setPlayer(1)
  props.setStart(true)
  
  props.setQ1(0)
  props.setW1(0)
  props.setE1(0)
  props.setR1(0)
  props.setT1(0)
  props.setY1(0)
  props.setU1(0)
  props.setI1(0)
  props.setO1(0)
  props.setP1(0)
  props.setA1(0)
  props.setS1(0)
  props.setD1(0)
  props.setF1(0)
  props.setG1(0)
  props.setH1(0)
  props.setJ1(0)
  props.setK1(0)
  props.setL1(0)
  props.setZ1(0)
  props.setX1(0)
  props.setC1(0)
  props.setV1(0)
  props.setB1(0)
  props.setN1(0)
  props.setM1(0)
  props.setQ2(0)
  props.setW2(0)
  props.setE2(0)
  props.setR2(0)
  props.setT2(0)
  props.setY2(0)
  props.setU2(0)
  props.setI2(0)
  props.setO2(0)
  props.setP2(0)
  props.setA2(0)
  props.setS2(0)
  props.setD2(0)
  props.setF2(0)
  props.setG2(0)
  props.setH2(0)
  props.setJ2(0)
  props.setK2(0)
  props.setL2(0)
  props.setZ2(0)
  props.setX2(0)
  props.setC2(0)
  props.setV2(0)
  props.setB2(0)
  props.setN2(0)
  props.setM2(0)
}

export default resetGameTwoPlayer
